---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME:ZGxjdmFmbm1xCg==
  CLOUDINARY_KEY:MjcyOTIyMjE1NTU2Nzc5Cg==
  CLOUDINARY_SECRET:Wm5Demd0MUNzMEc3dGZzbm1RdGZ2cDhKQjlZCg==
  MAPBOX_TOKEN:c2suZXlKMUlqb2liVzkxYm1scllYTmhiR0ZyZFd4aElpd2lZU0k2SW1Oc2RqVmlPRGQyTmpBeE1YTXljVzgxWVhScU1HUnRZbW9pZlEuRU56SHpONFJSOXNTYl9kUEVyMmhUQQo=
  DB_URL:bW9uZ29kYitzcnY6Ly9zYWxha3VsYW1vdW5pa2EyNjpQOW02SVloN0R0akNhUVVEQG1vdW5pa2EtZGIuYWt4Z3c5OC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TW91bmlrYS1EQgo=
  SECRET:bW91bmlrYXNhbGFrdWxhCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: salakulamounika/camp1:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
